kit:
  name: "Oracle Service Bus"
  link: https://github.com/qubell-bazaar/component-service-bus
  applications:
    - name: "Service Bus"
      manifest: https://raw.github.com/qubell-bazaar/component-service-bus/master/component-oracle-db-xe.yml
  provider:
    name: "Qubell"
    link: http://qubell.com
  documentation:
    overview: |
      This application requires the following items to be configured in your environment:
        * Amazon EC2 or Rackspace CloudServers account;
        * Ports 1521, 8080 open on the ﬁrewall.
      Please refer to the Getting Started for step-by-step instructions on how to configure your environment.